### PR TITLE
Scroll to bottom when new message arrives.

### PR DESCRIPTION
**Pull request by HRankit**
I noticed that the div was not scrolling to the bottom most position when new message arrived. User had to scroll manually. Hence this commit. Great work BTW.

### CODE REVIEW

**Comment by Merwanedr** [comment]
Thanks for the PR, very helpful!

**Comment by HRankit** [comment]
@Merwanedr Do you have any plans to use vuetify?

**Comment by Merwanedr** [comment]
The app is already using Vuetify

**Comment by HRankit** [comment]
Haha. Just saw that, sorry about that.

**Comment by Merwanedr** [comment]
No problem man :)

**Pull request merged**
